server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh1
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
#            - After=2021-06-10T14:44:32.336+08:00[Asia/Shanghai]
#            - Cookie=username,xiaohui
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-gateway
    prefer-ip-address: true
    hostname: cloud-gateway-service
